<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>How to fix MySQL replication | xluffy&#39;s page</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    
    <header>

  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <nav>
    <ul>
      
      
      <li class="pull-left ">
        <a href="https://xluffy.github.io">/home/xluffy&#39;s page</a>
      </li>
      
      
      <li class="pull-left ">
        <a href="/categories/">~/categories</a>
      </li>
      
      
      <li class="pull-left ">
        <a href="https://github.com/xluffy/til/issues">~/til</a>
      </li>
      
      
      <li class="pull-left ">
        <a href="#">~/books</a>
      </li>
      

      
      
      <li class="pull-right">
        <a href="/index.xml">~/subscribe</a>
      </li>
      

    </ul>
  </nav>
</header>

  </head>

  <body>
    <br/>

<div class="article-meta">
<h1><span class="title">How to fix MySQL replication</span></h1>

<h2 class="date">2018/03/27</h2>
<p class="terms">
  
  
  Categories: <a href="/categories/mysql">mysql</a> 
  
  
  
  
</p>
</div>



<main>


<p>Khi vận hành một hệ thống MySQL replication, thì khi một server slave bị lỗi có nghĩa là dữ liệu giữa Slave và Master đã có sự sai lệch, và lúc đó Slave sẽ không còn tác dụng trong hệ thống nữa. Nhiệm vụ của người vận hành hệ thống là cần fix để đưa slave quay trở lại hoạt động bình thường.</p>

<p>Có nhiều cách để fix slave tùy vào từng trường hợp cụ thể, một trong những yêu cầu cần thiết để có thể giải quyết nhanh chóng khi hệ thống M-S bị lỗi đó là bạn phải <strong>hiểu</strong> dữ liệu của bạn, phải biết là table đó làm gì, dữ liệu lưu trong đó có tác dụng gì, phục vụ cho chức năng nào, yêu cầu độ chính xác của dữ liệu đó ra sao thì mới có hướng giải quyết cụ thể.</p>

<p>Cơ bản sẽ có 2 phương pháp chính:</p>

<ul>
<li>Stop slave và rebuild lại slave mới -&gt; đây là cách dễ nhất mà không cần hiểu data, nhưng đi kèm đó là tốn rất nhiều thời gian nếu dữ liệu khá lớn.</li>
<li>Phân tích binlog và fix trên quá trình sync dữ liệu -&gt; cách này giúp recovery slave một cách cực kỳ nhanh chóng với các hệ thống có dữ liệu lớn, nhưng đòi hỏi cần phải hiểu về dữ liệu của chính mình.</li>
</ul>

<h2 id="1-rebuild-new-slave-with-mysqldump">1. Rebuild new slave with mysqldump</h2>

<p>Rebuild lại một slave cũng tương tự như cách chúng ta setup một hệ thống MySQL replication từ đầu, chỉ khác một điểm đó là <strong>hệ thống hiện tại đang online</strong> và bất cứ hành đồng nào tác động đến Master server đều ảnh hưởng trực tiếp tới người dùng. Với phương pháp này ta cần dùng <code>mysqldump</code> để dump dữ liệu ra sql file và đồng bộ dữ liệu, mình tóm gọn nó trong vào bước như sau:</p>

<pre><code>## Master
mysql&gt; FLUSH TABLES WITH READ LOCK;
mysql&gt; SHOW MASTER STATUS;

&gt; mysqldump -uroot -p dwh_prod &gt; dwh_prod_03072015.sql
&gt; rsync -avz -P -e'ssh' dwh_prod_03072015.sql root@172.17.0.2:/root/

## New Slave
&gt; mysql -uroot -p dwh_prod &lt; /root/dwh_prod_03072015.sql

mysql&gt; CHANGE MASTER TO MASTER_HOST='172.17.0.1',MASTER_USER='slave_user', MASTER_PASSWORD='p@ssword', MASTER_LOG_FILE='m01-bin.000001', MASTER_LOG_POS=827;
mysql&gt; START SLAVE
mysql&gt; SHOW SLAVE STATUS\G
</code></pre>

<p>Điểm lưu ý duy nhất như mình nói ở trên là việc lock table ở master sẽ ảnh hưởng trực tiếp tới người dùng nên phương pháp này chỉ nên sử dụng trong thời gian bảo trì hệ thống và <strong>nếu dữ liệu càng lớn, thời gian dump càng lâu thì hệ thống càng phải bảo trì lâu</strong>.</p>

<h2 id="2-rebuild-new-slave-with-xtrabackup">2. Rebuild new slave with xtrabackup</h2>

<p><code>xtrabackup</code> là một công cụ viết bằng C của Percona, thường được dùng để hotbackup MySQL, ưu/nhược điểm của nó so với <code>mysqldump</code> là:</p>

<ul>
<li>Không cần bảo trì hệ thống, không lock db và không ảnh hưởng tới người dùng.</li>
<li>Quá trình backup nhanh hơn rất nhiều so với <code>mysqldump</code>.</li>
<li>Nhược điểm là thư mục backup có kích thước chính bằng data-raw, trong khi dump sql thì rất nhẹ.</li>
</ul>

<p>Với các hệ thống có CSDL lớn thì dùng <code>xtrabackup</code> là giải pháp hoàn hảo cho việc backup cũng như rebuild 1 slave server vừa <strong>không ảnh hưởng</strong> tới hệ thống đang chạy, <strong>vừa nhanh</strong> hơn so với phương pháp truyền thống. Cụ thể gồm 2 bước như sau:</p>

<ul>
<li>Backup và restore dữ liệu với <code>xtrabackup</code>.</li>
<li>Point slave tới binlog và position của binlog trên master và sync dữ liệu.</li>
</ul>

<p>Để backup và restore dữ liệu với <code>xtrabackup</code> ta có 3 bước cơ bản như sau:</p>

<p>Backup toàn bộ data của mysql master với lệnh:</p>

<pre><code>&gt; xtrabackup --backup --target-dir=/backup/data
</code></pre>

<p>=&gt; ở đây mình đã cấu hình user/pass của root user trong file <code>~/.my.cnf</code> nên không cần phải pass thông tin này khi chạy <code>xtrabackup</code>, và có thể chạy với tùy chọn <code>--compact</code> để giảm kích thước khi backup.</p>

<p>Sync data qua slave và chạy prepare data:</p>

<pre><code>&gt; xtrabackup --prepare --rebuild-indexes --target-dir=/backup/data/

InnoDB: Starting shutdown...
InnoDB: Shutdown completed; log sequence number 22528643996
180329 14:48:04 completed OK!
</code></pre>

<p>=&gt; trong quá trình backup, có thể có những uncommited transaction không hoàn thành hoặc các transaction trong log cần phải được relay -&gt; quá trình này nhằm đảm bảo tính nhất quán của dữ liệu. Cũng có thể sử dụng thêm tùy chọn <code>--rebuild-threads=16</code> để tạo nhiều worker-theard để rebuild-index tại cùng một thời điểm.</p>

<p>Restore dữ liệu và start mysql</p>

<pre><code>&gt; service mysql stop
&gt; rm -rf /var/lib/mysql/
&gt; xtrabackup --copy-back --target-dir=/backup/data/

&gt; chown -R mysql: /var/lib/mysql
</code></pre>

<p>=&gt; Đây là quá trình chép ngược data backup vào datadir, cần lưu ý là datadir phải rỗng hoàn toàn trước khi copy-back.</p>

<p>Sau 3 bước trên là quá trình backup và restore dữ liệu đã hoàn thành, việc còn lại là đồng bộ hóa dữ liệu với master để thực hiện quá trình sync.</p>

<p>Sau khi copy-back xong, trong thư mục <code>/var/lib/mysql</code> sẽ có 1 file <code>xtrabackup_binlog_info</code>, file này chứa thông tin về binlog và position cần dùng để sync.</p>

<pre><code>&gt; cat /var/lib/mysql/xtrabackup_binlog_info

mysql-bin.000209    713297953
</code></pre>

<p>Và cấu hình sync từ master như cách bình thường trong <code>mysqldump</code> là được</p>

<pre><code>&gt; CHANGE MASTER TO MASTER_HOST='172.17.0.1',MASTER_USER='slave_user', MASTER_PASSWORD='p@ssword', MASTER_LOG_FILE='mysql-bin.000209', MASTER_LOG_POS= 713297953;
&gt; START SLAVE
&gt; SHOW SLAVE STATUS\G
</code></pre>

<p>Lưu ý là <code>xtrabackup</code> được viết bằng C, <code>innobackupex</code> là một Perl script được symlink tới <code>xtrabackup</code>, hiện tại Percona khuyến khích chúng ta chuyển qua <code>xtrabackup</code> vì <code>innobackupex</code> không còn được phát triển nữa, tuy nhiên trong một số trường hợp ta sẽ vẫn cần tới nó.</p>

<h3 id="2-1-một-số-tips-với-xtrabackup">2.1 Một số tips với xtrabackup</h3>

<p>Nếu chịu đào xới documentt của <code>xtrabackup</code> bạn có thể tìm thấy khá nhiều thứ hữu ích trong nhiều tình huống khác nhau. Thực tế mình cũng đã gặp những tình huống đó và mới thấy sự powerful của <code>xtrabackup</code>.</p>

<p><strong>Backup và stream qua network</strong></p>

<p>Một tình huống đó là ổ cứng của server master có kích thước là 1TB, dữ liệu trong MySQL là &gt;500GB, nghĩa là để backup ra ổ hiện tại là <strong>không đủ chỗ chứa</strong>, việc gắn thêm ổ cứng sẽ rất mất thời gian với hệ thống bare-metal. Đơn giản ta có thể stream trực tiếp bản backup qua server slave như sau.</p>

<pre><code>## New slave
&gt; nc -l 9999 | cat - &gt; /data/backups/backup.tar
</code></pre>

<p>=&gt; sẽ mở một port 9999 và output ra một file archive.</p>

<pre><code>## Master
&gt; innobackupex --stream=tar ./ | nc 172.17.0.2 9999
</code></pre>

<p>=&gt; backup và gửi trực tiếp qua slave.</p>

<p>Như ta thấy, sau khi backup xong ta sẽ có một file archive trên slave, và việc còn lại chỉ là unarchive và restore data. NHƯNG ta cũng có thể giải nén luôn trong quá trình stream.</p>

<pre><code>## New Slave
&gt; nc -l 9999 | tar -ivxf -

## Master
&gt; innobackupex --stream=tar ./ | nc 172.17.0.2 9999
</code></pre>

<p><strong>Tạo newslave mới từ slave cũ</strong></p>

<p>Giả sử ta có một server Master, một server slave, nhưng vì lý do nào đó mà server slave cần bảo trì, ta sẽ cần build slave mới thay thế. Nhưng ta lại không muốn đụng tới server Master, ta có thể dễ dàng tạo slave mới từ server slave sắp bảo trì với <code>xtrabackup</code> như sau:</p>

<pre><code>## Old slave
&gt; xtrabackup --backup --slave-info --target-dir=/backup/data
</code></pre>

<p>Hoặc stream</p>

<pre><code>&gt; innobackupex --slave-info --stream=tar ./ | nc 172.17.0.2 9999
</code></pre>

<p>Điểm khác biệt duy nhất là binlog và position thay vì được lưu trên <code>xtrabackup_binlog_info</code> thì sẽ được lưu trong <code>xtrabackup_slave_info</code>, ta chỉ cần thực hiện prepare-data, restore và point slave mới tới master với thông tin trong file <code>xtrabackup_slave_info</code>.</p>

<h3 id="2-2-một-số-thông-tin-thực-tế">2.2 Một số thông tin thực tế</h3>

<ul>
<li>Data 500GB, dùng <code>xtrabackup</code> stream qua network tốn 93 phút, unachive file tar 420GB tốn 39 phút, <code>--prepare</code> tốn cỡ 60ph.</li>
<li>Data 500GB, dùng <code>xtrabackup</code> stream và unarchive trực tiếp cho tới khi build xong slave tốn ~2h.</li>
<li>Data 500GB, dùng <code>mysqldump</code> data ra đĩa, tốn 183 phút, file sql nặng 182GB chưa nén.</li>
</ul>

<h2 id="3-phân-tích-binlog-và-fix-trên-quá-trình-sync-dữ-liệu">3. Phân tích binlog và fix trên quá trình sync dữ liệu</h2>

<p>Nếu tìm kiếm trên Internet ta sẽ thấy có một số blog hướng dẫn fix replication data giữa M-S như sau:</p>

<pre><code>mysql&gt; STOP SLAVE; SET GLOBAL SQL_SLAVE_SKIP_COUNTER=1; START SLAVE; 
</code></pre>

<p>Tuy nhiên đây là một ý tưởng khá là tệ và tốt nhất là nên tránh sử dụng phương pháp này. Với câu lệnh trên, Slave sẽ bỏ qua lỗi đó và next tới transaction tiếp theo để apply binlog =&gt; mất tính nhất quán của dữ liệu.</p>

<p>Ví dụ:</p>

<ul>
<li>Ứng dụng quản lý tồn kho, các query read được đẩy vào Slave.</li>
<li>Một sản phẩm tồn kho còn 1, user sau khi mua số lượng 1, số tồn kho được trừ về 0 trên master.</li>
<li>Binlog sinh ra, sync qua slave và được apply vào slave nhưng bị lỗi.</li>
<li>Thực hiện skip qua transaction đó -&gt; số tồn kho của sản phẩm đó vẫn là 1 trên slave -&gt; và nếu không có thêm bất cứ tác động gì tới record đó thì slave vẫn hoạt động và sync data bình thường.</li>
</ul>

<p>=&gt; Khi có một user khác vào xem sản phẩm, phát sinh query đọc lên số lượng tồn kho từ slave và thông báo sản phẩm còn số lượng là 1. User thực hiện bỏ vào giỏ hàng (write data -&gt; gọi vào slave) =&gt; Không thể bỏ vào giỏ hàng do trên master lại kiểm tra là số lượng là 0.</p>

<p>Thực tế việc sử dụng như trên chỉ khi thực sự hiểu rằng data của chúng ta sẽ bị tác động như thế nào, ví dụ có nhiều ứng dụng lưu log request hoặc <code>push_notification_log</code> vào mysql thì ta hoàn toàn có thể SKIP nếu biết chắc chắn apply log vào các bảng dữ liệu trên.</p>

<p>Trong thực tế, trước đây mình gặp một vài tình huống khá kỳ cục, nhưng bằng cách là decode binlog mà mình đã giải quyết khá nhiều trường hợp mà không cần rebuild lại slave, tiết kiệm rất nhiều thời gian và công sức. Thường các trường hợp đó là:</p>

<ul>
<li>Kiểu dữ liệu của column, charet của bảng giữa slave và master không đồng nhất.</li>
<li>Dữ liệu một record trên slave khác master, hoặc index đã tồn tại trên slave.</li>
</ul>

<p>=&gt; những lỗi này thực ra chủ yếu do con người tạo ra, nhưng việc fix nhanh chóng vẫn là điều cần thiết.</p>

<p>Ví dụ 1:</p>

<pre><code>                Relay_Log_Pos: 619131881
        Relay_Master_Log_File: mysql-bin.000569
             Slave_IO_Running: Yes
            Slave_SQL_Running: No 
                   Last_Errno: 1061
                   Last_Error: Error 'Duplicate key name 'users_id_photo_idx'' ON query. DEFAULT DATABASE: 'facebook'. Query: 'CREATE INDEX `users_id_photo_idx` ON `users`(`id`, `photo_id`) USING BTREE'
</code></pre>

<p>=&gt; như ở trên báo lỗi ở file binlog là <code>mysql-bin.000569</code>, vị trí 619131881, ta sẽ cần decode binlog.</p>

<pre><code>&gt; mysqlbinlog --base64-output=DECODE-ROWS --verbose mysql-bin.000569 &gt; mysql-bin.000569.decode.sql
&gt; grep --color=always -A 30 619131881 decode.sql
</code></pre>

<p>=&gt; bản chất là không hiểu bằng cách nào đó, <code>users_id_photo_idx</code> đã tồn tại trên slave, và khi ta đánh index trên master, index này đc sync qua slave và apply thì báo lỗi đã tồn tại.</p>

<p>Cách fix đơn giản là xóa index <code>users_id_photo_idx</code> trên slave và slave lại replication là có thể fix.</p>

<p>Ví dụ 2:</p>

<pre><code> 				  Last_SQL_Errno: 1062
               Last_SQL_Error: Error 'Duplicate entry '5' for key 'PRIMARY'' on query. Default database: 'facebook'. \ 
               Query: 'INSERT INTO t VALUES (5,2)'
</code></pre>

<p>=&gt; Trên bảng <code>t</code> của slave đã tồn tại một record có <code>id</code> bằng 5, dẫn tới khi sync lệnh <code>INSERT</code> qua slave thì bị duplicate, đơn giản chỉ cần xóa record match đó đi <code>DELETE FROM t WHERE id = 5 AND pid = 2</code> và start lại slave.</p>

<p><strong>Tóm lại</strong> với cách này, việc fix slave là vô cùng nhanh chóng, chỉ tốn khoảng vài giây, vài phút và slave có thể quay trở lại hoạt động và bạn cũng không phải mất thời gian build lại slave và chờ sync kịp dữ liệu.</p>

</main>

    <footer>
      
<script>
(function() {
  function center_el(tagName) {
    var tags = document.getElementsByTagName(tagName), i, tag;
    for (i = 0; i < tags.length; i++) {
      tag = tags[i];
      var parent = tag.parentElement;
      
      if (parent.childNodes.length === 1) {
        
        if (parent.nodeName === 'A') {
          parent = parent.parentElement;
          if (parent.childNodes.length != 1) continue;
        }
        if (parent.nodeName === 'P') parent.style.textAlign = 'center';
      }
    }
  }
  var tagNames = ['img', 'embed', 'object'];
  for (var i = 0; i < tagNames.length; i++) {
    center_el(tagNames[i]);
  }
})();
</script>

      
      <hr/>
      <a href="https://github.com/xluffy">Github</a> | <a href="https://twitter.com/min0lta">Twitter</a> | <a href="https://t.me/xluffy">Telegram</a>
      
      <br><a href="https://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png"></a>
    </footer>
  </body>
</html>

